# Generated by Django 5.0 on 2023-12-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article_compleated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='compleated',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
